### ISSUE TITLE
Starting docker-compose containers with chamber exec

### ISSUE THREAD

**Issue by caseydm** [segmentio/chamber#114]
I have a working version of chamber on an Amazon Linux 2 install. I can run 'chamber list sentry' and see my environment variables. However, I am trying to start containers in docker-compose with all of my environment variables populated, but it is not working. 

This is my file so far. The error I get is 'web_1        | /bin/bash: chamber exec sentry --: No such file or directory. Any way to get this working?

```
version: '3.4'

x-defaults: &defaults
  restart: unless-stopped
  build: .
  depends_on:
    - redis
    - memcached
    - smtp
  entrypoint: ["/bin/bash", "chamber exec sentry --"]

  environment:
    SENTRY_MEMCACHED_HOST: memcached
    SENTRY_REDIS_HOST: redis
    SENTRY_EMAIL_HOST: smtp
  volumes:
    - sentry-data:/var/lib/sentry/files


services:
  smtp:
    restart: unless-stopped
    image: tianon/exim4

  memcached:
    restart: unless-stopped
    image: memcached:1.4

  redis:
    restart: unless-stopped
    image: redis:3.2-alpine

  web:
    <<: *defaults
    ports:
      - '9000:9000'

  cron:
    <<: *defaults
    command: run cron

  worker:
    <<: *defaults
    command: run worker


volumes:
    sentry-data:

```
