### ISSUE TITLE
Add ability to deploy configs from the configuration file

### ISSUE THREAD

**Issue by adikari** [segmentio/chamber#362]
It would be nice to have a configuration file to manage an application's configuration file where all the configs are defined. Then, when you run `chamber run`, it reads all the configuration in the configuration file and deploys to `ssm`.

I built a tool called [oprah](https://github.com/adikari/oprah) a while back which allowed exactly that. The configuration could look something like:

```
provider: ssm

defaults:
  path: /${STAGE}/gateway/

params:
  - name: DB_NAME
    description: 'database name'
    value: database-name
    override:
      production: production-database-name
      staging: staging-database-name

  - name: DB_PASSWORD
    description: 'database password'
    secret: true

  - name: DB_PORT
    required: false

  - name: DATADOG_API_KEY
    path: /shared/
    secret: true
```

With the above config all configs would be deployed under path `/stage/gateway` and would look something like `/stage/gateway/DB_NAME`. For any configs which has overwritten path then the default prefix would not be used. 

For the non-secret configs, you can simply put the value in the file. For the secrets, the chamber will prompt the user to enter the value during the run. 

Let me know what your thoughts are regarding this feature and if that's something you would like to add to the chamber. I am happy to work on it if that's something you would consider.

Thanks
