### ISSUE TITLE
Serialize YAML and JSON into string -> cannot unmarshal !!seq !!map into string

### ISSUE THREAD

**Issue by 1oglop1** [segmentio/chamber#438]
Hi, what's the reason I could not import a simple config like this?

```yaml
ch_secret: secret
ch_list:
  - https://develop.dofinansowania-stx.pl
ch_dict:
  a: abc
  b: def
ch_dict_nested:
  a:
    b: abc
    c: def

ch_dict_list:
  c: 
    - 1
    - 2
    - 3

ch_mix:
  a:
    b: abc
    c: def
  c: 
    - 1
    - 2
    - 3
    ```
Error: Failed to decode input as json: yaml: unmarshal errors:
  line 3: cannot unmarshal !!seq into string
  line 6: cannot unmarshal !!map into string
  line 10: cannot unmarshal !!map into string
  line 16: cannot unmarshal !!map into string
  line 23: cannot unmarshal !!map into string

**Comment by alecjacobs5401** [comment]
This is likely failing because [we don't support complex nested yaml files for import](https://github.com/segmentio/chamber/blob/ac412f5e35c63ceeae299a5576ae168acb11ad65/cmd/import.go#L49-L54). Currently, a flat file structure is expected like so

```yaml
ch_secret: secret
other_secret: other_secret
```

**Comment by 1oglop1** [comment]
any chance you, consider supporting nested config? I'd like to dump some JSON into SSM.
Otherwise, a better error message is also an acceptable solution.

**Comment by alecjacobs5401** [comment]
I'd like to understand what problem you're trying to solve for?

If you want raw JSON as a value, you could provide a JSON string as the value as a workaround

**Comment by 1oglop1** [comment]
That workaround is exactly what I'm trying to avoid.

So far I've been deploing stuff with pulumi but I am trying to move some
values from pulumi config to SSM and this inconvenience is the only thing
preventing me. Otherwise I'd have to write my own cli for setting the
parameters.


I understand it can get complicated because the nested value can be
serialized into string but what should happen during the export or exec.

**Comment by alecjacobs5401** [comment]
Just trying to fully understand what you're looking for - you'd like `chamber import` to support nested structures and manage serializing it out into a JSON object to write to SSM, correct? Are you expecting that reading the value or exporting it does the same?

**Comment by 1oglop1** [comment]
Yes, that's what I expect.

Here's a  more detailed description of my explanation:

input
```
ch_secret: secret
ch_list:
  - https://abc.def.com
ch_dict:
  a: abc
  b: def
ch_dict_nested:
  a:
    b: abc
    c: def

ch_dict_list:
  c: 
    - 1
    - 2
    - 3

ch_mix:
  a:
    b: abc
    c: def
  c: 
    - 1
    - 2
    - 3
    ```
